### ISSUE TITLE
assertInt is quite errorprone

### ISSUE THREAD

**Issue by berndbischl** [mllg/checkmate#103]
many people use this in places where they should use asInt

what then happens are hard to guard against runtime errors when users say foo=1

yes, the user can still say foo=1L, but this type of error is pretty confusing to many people

NB: i am unsure about the best solution....

**Comment by berndbischl** [comment]
see discussion here

https://github.com/mlr-org/mlrMBO/issues/374#issuecomment-287063966

**Comment by berndbischl** [comment]
also, the name of asInt is kinda bad, we somebody else posted this here in the tracker IIRC

why dont you use the return value of assertInt? 
I mean currently it return a double. 
change that to returning a changed int. 
then i can write
x = assertInt(x)

and asInt can be removed?

**Comment by berndbischl** [comment]
for completeness:

that looks very inconsistent

```
> assertInt(1)
> assertInteger(1)
Error in assertInteger(1) : 
  Assertion on '1' failed: Must be of type 'integer', not 'double'.
```

**Comment by jakob-r** [comment]
I think it is intuitive and well documented. `assertInt` is less strict then `assertInterger` - that's why it's shorter. It's also shorter because it's meant for a single value and not for a vector.

**Comment by berndbischl** [comment]
> I think it is intuitive

sorry..... you can argue that its documented. the last post above is very certainly not intuitive.
especially as R does not even have scalars. and 1 = c(1).
now one COULD argue that there is a difference here in normal usage. 
but nobody can see that from the name. 

we can then all go back to using sapply. thats also documented what it does.

**Comment by berndbischl** [comment]
i also ran gblame on the bug. unfortunately it was the other @jakobbossek who wrote the wrong check :)

**Comment by jakob-r** [comment]
> and asInt can be removed?
assert* never changes the type

```r
> x = assertInt(3)
> class(x)
[1] "numeric"
```

asInt does change the type.

Also: What behaviour are you exactly expecting from which function?

**Comment by berndbischl** [comment]
the point is this:

1) asInt has a quite confusing name. Other people already "complained" about it here.
a) In R there is as.integer (which does something else)
b) from asInt you would expect a normal type conversion, not (mainly) calling this for the side effect of arg checking.

2) I know which function does which. 
(I got confused for a few minutes due to the names and somewhat inconsistensies, hence my posting here....) 
Also, older versions of cm::asssertInt did not let "1" pass. Michel changed this due to related problems I think. 

3) Yes, the assert* don't change type. 
Question is, whether assertInt(x) SHOULD change type of x to int. Where is the hurt? Why would I want to *rely* on it not being changed? 
If it does change type for "integerish" x input to normal int, here are 2 possible advantages:
a) asInt can deprecated, and the "confusing name problem is gone". also one function less is always good, if you dont need it. 
b) you can now use the idiom
x = assertInt(x)
which now is indeed a true assertion in the sense that x is a real int after that line. 


I have written too many post about the "int" functions in the past already. Let's wait for Michel

**Comment by mllg** [comment]
* I think conversion is generally not in the scope of checkmate, checkmate is for checks/assertions.
* I completely disagree that `assert*` functions should do any conversion. They solely have a return value to integrate them into compound statements (`f(assertString(x))`) or pipelines `... %>% assert_data_frame(x, ncol = 4) %>% ...`).
* `assertInt` never threw an error for integerish doubles. I've tested with checkmate-1.0.0. I've changed assertions though. They did not have a return value in early versions of checkmate.
* Integers are typically used for `size_t`-like variables, and `assertCount` is more precise in these cases.

Despite the rather unfortunate  name `assertInt`, I do not see a problem here. I would rather argue to deprecate the `as*` functions and create a small extension package (convertmate?) for frequently used conversions such as
* converting double -> int
* converting factor <-> character
* converting lists <-> data.frame
* converting rows to list
* converting vector of objects to list of other objects using a constructor function (e.g., character to list of learners using `mlr::makeLearner`).

**Comment by berndbischl** [comment]
please write down how in your opinion the input check should look like

function(my_count)

**Comment by berndbischl** [comment]
you can make up any new function you like

**Comment by berndbischl** [comment]
1) assertCount(my_count)?
now for my_count=1, that is an "untrue" statement. 
also consider what happens if i pass down to C.
i either get an error or have to write as.integer(my_count)

2) assertCount(x); x = as.integer(x)
looks very weird. also very verbose. i also dont see what "convertmate" now helps me for. i already have  "as.integer". or are you suggesting to have the "argcheck+convert" in there? 
that would be OK IMHO

**Comment by mllg** [comment]
I guess I would use `asCount(x)` (which is arg check + convert) if I want to do a conversion or else use `assertCount(x)` if the next operations do not distinguish between int/double, e.g. ">".

**Comment by mllg** [comment]
Oh, probably I did not get your point before. The extra package would use checkmate for argcheck before conversion - similar to `as*` functions in checkmate now. I would just clearly separate into different packages for different purposes which usually helps to not mix up functions.

**Comment by berndbischl** [comment]
> if the next operations do not distinguish between int/double, e.g. ">".

well that is always very hard to know right? as you have to know that also about EVERY piece of client code that gets called later, which you dont control?

> Oh, probably I did not get your point before. The extra package would use checkmate for argcheck before conversion - similar to as* functions in checkmate now. I would just clearly separate into

not sure that i see the need for the extra, very small package. but that of course would also be totally ok. 
in the end i would probably "lint out" all uses of assertInt(x) or assertCount(x) in my packages then. because i can really not see a use-case where i dont want x to be a double after the assertion.....

**Comment by mllg** [comment]
> well that is always very hard to know right? as you have to know that also about EVERY piece of client code that gets called later, which you dont control?

If I'm unsure, I can still convert. And 99% of the code I do not control does not distinguish between double/int. `data.table` is the only exception that comes to my mind.


> in the end i would probably "lint out" all uses of assertInt(x) or assertCount(x) in my packages then. because i can really not see a use-case where i dont want x to be a double after the assertion.....

That's totally fine.

**Comment by berndbischl** [comment]
> ata.table is the only exception that comes to my mind.

after 1 sec of thought: xgboost

**Comment by mllg** [comment]
I've added hints to the documentation to make it clear that `assert*` will not convert to integer. I don't see any other working solutions.
