### ISSUE TITLE
character regex w/ NA elements

### ISSUE THREAD

**Issue by wibeasley** [mllg/checkmate#106]
(Also see http://stackoverflow.com/questions/43455295/checkmate-w-na-elements, and the comments/responses.)

I'd like to determine if all elements in a character vector either (a) are NA or (b) conform to the regex pattern. (In this specific case, an element may contain only digits.)

The call below returns "Assertion on 'x' failed: Must comply to pattern '^\d{2,3}$'", even with the `any.missing` parameter set to TRUE. 

```r
x <- c("11", "22", "333", NA_character_)
pattern <- "^\\d{2,3}$"

checkmate::assert_character(x,  pattern=pattern, any.missing=TRUE)
```
1. Is this the intended behavior of a regex + `any.missing`?
1. Is there a natural & concise way to test this w/ checkmate? 
1. Is the any.missing parameter essentially ignored if a regex pattern is used?

For reference, a similar expression using [testit](https://CRAN.R-project.org/package=testit) is

```r
testit::assert(
  "Any existing elements must be missing or only digits",
  all(is.na(x) | grepl(pattern, x)
)
```

**Comment by mllg** [comment]
You are right, missing values should be ignored in regex matching. I've fixed the function and clarified the docs.
