### ISSUE TITLE
ignore missing values for string's `min.chars` argument

### ISSUE THREAD

**Issue by wibeasley** [mllg/checkmate#111]
Similar to #106 & #110, should the `min.chars` be applied only to the nonmissing values?  In other words, should this assertion pass?
```r
s <- c(letters, NA_character_)
checkmate::assert_character(s, min.chars = 1, any.missing = T)
```

It currently fails w/ 
>Error in checkmate::assert_character(s, min.chars = 1, any.missing = T) : 
  Assertion on 's' failed: All elements must have at least 1 characters.

It looks like this is controlled in the package's [C code](https://github.com/mllg/checkmate/blob/e193706bde3516a0e99ce47a2c0e2fa1c5ba3d1d/src/checks.c#L147), and I'm too chicken to try it.

**Comment by mllg** [comment]
Good point, fixed now.
