### ISSUE TITLE
assert() might have an 'add' argument

### ISSUE THREAD

**Issue by tdeenes** [mllg/checkmate#112]
Is there a particular reason why assert() does not have an 'add' argument?
Here is a toy example:
`
AC <- makeAssertCollection()
x <- "wrong_argument"
assert(checkInteger(x), checkLogical(x), combine = "or", add = AC) 
`

**Comment by LudvigOlsen** [comment]
I'm wondering about this as well?
Is there a common approach for adding "or" checks to the collection? :)

**Comment by mllg** [comment]
I personally do not use collections, so I just forgot to implement it. If there is still interest in it, a PR would be welcome.

**Comment by tdeenes** [comment]
I implemented it once in a private package; will check it soon and create a PR.

**Comment by mllg** [comment]
Thanks for the PR. Do you want to add yourself as contributor to the DESCRIPTION?

**Comment by tdeenes** [comment]
@mllg 
Thanks for the offer. BTW, do you have any explicit policy for contributing to `checkmate`? I mean something like this one: https://github.com/Rdatatable/data.table/wiki/Contributing

**Comment by mllg** [comment]
No, there is no policy. I guess it would be helpful for new contributors. OTOH, checkmate is a much smaller project than data.table (or mlr3 where we have similar policies) and I have no problem reformatting a PR, adding some more tests or assisting in troubleshooting for checkmate.
