### ISSUE TITLE
Check for mandatory names in assert_names()

### ISSUE THREAD

**Issue by MansMeg** [mllg/checkmate#116]
Hi!

Thanks again for a great package! 

I find myself writing the following type of code a lot:
```
checkmate::assert_names(c("variable_1", "variable_2"), subset.of = names(my_data.frame))
```
To assert that certain variables exist within a data.frame. This makes the error message look a little bit funky, so I have a suggestion to add something like this:

```
checkmate::assert_names(names(my_data.frame), must.include = c("variable_1", "variable_2"))
```

It works without, but it would be a nice addition!

**Comment by mllg** [comment]
Thanks, now implemented on the base branch.
