### ISSUE TITLE
several `NA`s fail unique tests

### ISSUE THREAD

**Issue by maxheld83** [mllg/checkmate#122]
```
assert_list(x = list(foo = NA, bar = NA, zap = "hello"), unique = TRUE)
```

Not 100% sure what the consistent, proper thing here is, but it's odd to me that this fails because of the `NA`s. 

Are `NA`s non-unique?

My expectation would have been that the test ignores `NA`s, but again, might not know the bigger picture.

**Comment by mllg** [comment]
> Are NAs non-unique?

Yes, R does indeed distinguish between NA, NA_integer_, NA_real_, NA_complex_ and NA_character_.
Internally I'm calling R's `unique()` which behaves the same:
```r
length(unique(list(a = NA, b = NA_real_)))
[1] 2
```
Note that this **only** applies to lists, in atomic vectors the NAs are coerced to the same type.

Repairing this would likely require (a) some thousand lines of C code to re-implement `unique()` efficiently with a hash table or (b) some rather expensive operation in R. Still unsure what to do with this...
