### ISSUE TITLE
`check_integerish()` gives uninformative error messages for big integers.

### ISSUE THREAD

**Issue by rorynolan** [mllg/checkmate#127]
I realise now that this is because the max value of an `int` was breached, but it would be useful if `checkmate` told you this itself. Indeed I think "big integers" should be classed as "integerish".

``` r
library(checkmate)
check_integerish(1)
#> [1] TRUE
check_integerish(100)
#> [1] TRUE
2 ^ 30
#> [1] 1073741824
check_integerish(2 ^ 30)
#> [1] TRUE
.Machine$integer.max
#> [1] 2147483647
check_integerish(.Machine$integer.max)
#> [1] TRUE
check_integerish(.Machine$integer.max + 1)
#> [1] "Must be of type 'integerish', not 'double'"
check_integerish(2^31)
#> [1] "Must be of type 'integerish', not 'double'"
check_integerish(2^32)
#> [1] "Must be of type 'integerish', not 'double'"
```

**Comment by rorynolan** [comment]
I understand your mindset. I'm not saying `check_integerish()` should return `TRUE` for integers outside the `int` range, just that the message should be more informative. Something like "Must be of type 'integerish', not 'double'. Your number may seem integerish but it is outside the 32-bit `int` range, which is [-2147483648, 2147483647]".

**Comment by mllg** [comment]
I have improved the error message. Thanks for pointing me to this.

**Comment by rorynolan** [comment]
Thanks for implementing my suggestion. I love `checkmate` and I depend on it for all my packages!
