### ISSUE TITLE
optionally return index of offending element with error message

### ISSUE THREAD

**Issue by maxheld83** [mllg/checkmate#129]
When used, for example, for input-validation in user-facing functions in packages, it might be helpful for error messages to include the *index* of the offending element (say, a row/column in a matrix, or element-number in a list), as the [tidyverse style guide](http://style.tidyverse.org/error-messages.html) advises.

Checkmate does not currently do this for, say, `checkmate::assert_matrix(any.missing = FALSE, ...)`.

I've asked over at [StackExchange](https://stackoverflow.com/questions/48591323/how-to-report-error-indices-in-r), how to tack this on to existing assertions elegantly, but also wondered whether this might be something that checkmate could support out of the box.

I'm in no position to say whether this is out of scope, or not in line with checkmate's philosophy, just wanted to hear what your thoughts on this were, and whether others are having the same problem.

It seems to me that if we want to have better error messages (for users) across the board, we might need some scaffolding here to make it easier.

**Comment by mllg** [comment]
Returning the first offending element is possible w/o loosing speed but will require some restructuring. Will do as soon as I find some spare time.

**Comment by mllg** [comment]
This is implemented in e10ff25c2e4a6aa43f5895bb84bd70e4dc2c0f10.
