### ISSUE TITLE
integers allowed in `checkNumeric()`

### ISSUE THREAD

**Issue by wibeasley** [mllg/checkmate#131]
Is the intended behavior of [`checkNumeric()`](https://github.com/mllg/checkmate/blob/master/R/checkNumeric.R) when passed integers?

```r
> checkmate::checkNumeric(c(2L, 4L))
[1] TRUE
```

https://github.com/mllg/checkmate/blob/32f607ccfed2dd328ecb2398d3d65f62e68f891e/src/checks.c#L575

**Comment by mllg** [comment]
It seems odd, but this is intended. Compare with
```r
is.numeric(2L)
```
If you happen to need something like `checkDouble` (c.f. `is.double`) let me know.

**Comment by wibeasley** [comment]
@mllg, I would use it, because I like to detect slight differences in the data uploading into a database/pipeline.  I didn't realize `is.numeric()` would be ok with a value like '2L' --I guess because it's easily coerce-able?  Things like `dplyr::coalesce()` aren't as forgiving, which I guess is my preference.

```r
> dplyr::coalesce(2L, 3.1)
Error: Argument 2 must be type integer, not double
```

Would you like me to try a PR?

**Comment by mllg** [comment]
Thanks for offering a PR, but this was basically 5 minutes of copy-paste. I will try to prepare a new release before R-3.5.0.

**Comment by wibeasley** [comment]
@mllg, thanks.  I had [started it a few days ago](https://github.com/wibeasley/checkmate/commit/88024cd7ebba53310026fa40898e61f24e9a275b) but probably wasn't close to finishing it.  

I'm curious, were all those [new elements in checks.c](https://github.com/mllg/checkmate/commit/44a5769198966cffed085634a10304896165a90f) related to `checkDouble()`?

**Comment by mllg** [comment]
Whops, I accidentally checked in a duplicate of `checks.c` in the root package directory. This obfuscated the diff. Here are the actual changes: <https://github.com/mllg/checkmate/commit/44a5769198966cffed085634a10304896165a90f#diff-3c6b2175d1b21f4bade977f033c8280e>
