### ISSUE TITLE
makeAssertionFunction() should produce function that includes checkmate:: prefix

### ISSUE THREAD

**Issue by rickhelmus** [mllg/checkmate#139]
Hello,

Currently `makeAssertionFunction()` will not include the package namespace when creating its output function:
```R
checkmate::makeAssertionFunction(checkmate::checkNumber)

# results in
function (x, na.ok = FALSE, lower = -Inf, upper = Inf, finite = FALSE, 
    null.ok = FALSE, .var.name = vname(x), add = NULL) 
{
    res = checkmate::checkNumber(x, na.ok, lower, upper, finite, 
        null.ok)
    makeAssertion(x, res, .var.name, add)
}
```

Hence, this function will give an error that `makeAssertion` cannot be found if `checkmate` is not imported in the namespace.

--
EDIT: Spoke a bit too soon. Using `makeAssertion()` will cause similar issues... I guess `checkmate` has to be (partially) imported for now...

**Comment by mllg** [comment]
f69b8bb7579aa0612c87247c719ace7c2c6e4a97 should work around this. Can you confirm?

**Comment by rickhelmus** [comment]
Excellent! Seems to work fine. Thanks for the quick fix.
