### ISSUE TITLE
checkFunction with nargs fails for primitive functions

### ISSUE THREAD

**Issue by mb706** [mllg/checkmate#144]
`checkFunction` queries the function arguments using `formals`, but for `.Primitive` functions this [returns `NULL`](https://cran.r-project.org/doc/manuals/r-release/R-ints.html#g_t_002eInternal-vs-_002ePrimitive). Instead of `formals(x)`, one should probably use `formals(args(x))`.

```R
> checkFunction(as.logical, nargs = 1)
[1] "Must have exactly 1 formal arguments, but has 0"
```

**Comment by mllg** [comment]
Thanks, should be fixed now.
