### ISSUE TITLE
`checkmate` throws errors from wrong function in `knitr` Rmarkdown chunks with `error=TRUE`

### ISSUE THREAD

**Issue by rorynolan** [mllg/checkmate#151]
Checkmate appears to throw an error from the wrong function in Rmarkdown chunks. When I knit the following

```
---
title: "Checkmate Rmarkdown"
date: "29/08/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r checkmate, error=TRUE}
errfn_checkmate <- function(x) {
  checkmate::assert_character(x)
}
errfn_checkmate(1)
```

```{r other-error, error=TRUE}
errfn <- function() {
  stop("error")
}
errfn()
```

I get 

__Checkmate Rmarkdown__
29/08/2018
```
errfn_checkmate <- function(x) {
  checkmate::assert_character(x)
}
errfn_checkmate(1)
## Error in rmarkdown::render("/Users/rnolan/Dropbox/R/strex/vignettes/checkmate.Rmd", : Assertion on 'x' failed: Must be of type 'character', not 'double'.
errfn <- function() {
  stop("error")
}
errfn()
## Error in errfn(): error
```

So you can see that checkmate is throwing an error from `rmarkdown::render()`, where it should be throwing an error from `errfn_checkmate()`. There's no such difficulty with `errfn()` which errors with `stop()` directly.

**Comment by mllg** [comment]
Are you using the release or devel verison of checkmate? The behavior has changed (c.f. #117).

**Comment by rorynolan** [comment]
Right you are, silly me, should've tried with devel. Sorry for bothering you.

**Comment by mllg** [comment]
No worries! :smiley:
