### ISSUE TITLE
POSIXct not supported in 1.8.5

### ISSUE THREAD

**Issue by tcornwall** [mllg/checkmate#153]
When I try to run:
checkmate::qtest(1, 'P'), I get the following error message:

Error in qtest(1, "P") : Unknown class identifier 'P'. 

Unlike the online helpfile, my local help does not contain a reference to posixCT dates.

This is running checkmate_1.8.5. Possibly related to #138 ?

**Comment by mllg** [comment]
I forgot to mention it in the news. The change is in 1.9.0. A new release is overdue, I'm still waiting for some reverse dependencies to be updated on CRAN though.

**Comment by tcornwall** [comment]
Cool, thanks for letting me know.

Really enjoy using checkmate, by the way.

Best,
Tom
