### ISSUE TITLE
assert file path suffixes

### ISSUE THREAD

**Issue by MansMeg** [mllg/checkmate#162]
Hi!

First of all, your package is the best. I now use it in all my packages. I just realized I would be happy to assert the suffix of a file path. Say, something like this

```
path <- "my_txt_file.txt"
checkmate::assert_path_for_output(path, file_suffix = "txt")
```

**Comment by mllg** [comment]
I'm confused now. Do you mean prefix or suffix?

**Comment by MansMeg** [comment]
Oh. Sorry I meant a suffix!
