### ISSUE TITLE
update checkmate on CRAN

### ISSUE THREAD

**Issue by LiNk-NY** [mllg/checkmate#163]
Hi Michael, @mllg 

I keep getting a surprise dependency with the CRAN installation of this package. 

I see that the version on GitHub is different. Can you push it up to `CRAN` (`1.9.3`)?

Best regards,
Marcel

**Comment by mllg** [comment]
> I keep getting a surprise dependency with the CRAN installation of this package.

What do you mean by surprise dependency? 

I'm actually in the process of updating checkmate on CRAN. I uploaded yesterday, but broke some reverse dependencies. After this is fixed, I will re-upload again.

**Comment by LiNk-NY** [comment]
Sorry, I had mixed my installation folders. 
But thanks for uploading to CRAN.
