### ISSUE TITLE
Add 'factor.ok' to checkIntegerish()

### ISSUE THREAD

**Issue by tdeenes** [mllg/checkmate#164]
I find the following result counter-intuitive:
```r
> checkmate::testIntegerish(factor(letters))
[1] TRUE
```
Of course a factor is internally a set of integer values with a "levels" attribute, but I can not think of a use case where I would want to consider a factor an integerish vector. Since *checkmate* returns TRUE currently, I suggest to add a `factor.ok` argument to `checkIntegerish()` and friends which would default to `TRUE` to avoid a breaking change.

@mllg , if you agree, I am happy to submit a PR.

**Comment by mllg** [comment]
I would consider this a bug. I already have a PR and I'm running reverse dependency checks.

**Comment by mllg** [comment]
Merged and fixed, thanks for reporting.
