### ISSUE TITLE
missing images in "Getting started" vignette

### ISSUE THREAD

**Issue by espinielli** [mllg/checkmate#168]
This is to report that all images in "Getting started" page [1] are missing.
Here is a screenshot 

![missing-img-checkmate](https://user-images.githubusercontent.com/891692/62356255-ef46a780-b510-11e9-80e1-97ece9dde1b5.png)

[1] https://mllg.github.io/checkmate/articles/checkmate.html

**Comment by mllg** [comment]
Thanks! Should be fixed now.
