### ISSUE TITLE
asserting integer valued numeric values with 0 tolerance

### ISSUE THREAD

**Issue by mb706** [mllg/checkmate#177]
I want to make sure a given value, possibly `numeric` storage type, is an integer in the mathematical sense. I would use `assertInt()` for scalars or `assertIntegerish()` for vectors, but they have a tolerance of `sqrt(eps)` by default. If I set the tolerance to 0, however, the test fails for all `numeric`s:
```r
> checkmate::assertIntegerish(100.00000001)  # I'd want this to throw an error
> checkmate::assertIntegerish(1000, tol = 0)  # this doesn't work
Error: Assertion on '1000' failed: Must be of type 'integerish', but element 1 is not close to an integer.
```

**Comment by mb706** [comment]
in fact zero tolerance should probably be the default behaviour but I guess it is too late for that.

**Comment by mllg** [comment]
Can you give an example why you need it?

**Comment by mb706** [comment]
```r
myFunction(1) # no error
myFunction(1.000000001) # error
```

**Comment by mb706** [comment]
assertInt(x)
myarray[x]

**Comment by tdeenes** [comment]
@mb706 
I think your request does not relate to checkmate. Are you aware of [this FAQ](https://cran.r-project.org/doc/FAQ/R-FAQ.html#Why-doesn_0027t-R-think-these-numbers-are-equal_003f)?

The take-home message is:

> The only numbers that can be represented exactly in R’s numeric type are integers and fractions whose denominator is a power of 2. All other numbers are internally rounded to (typically) 53 binary digits accuracy. As a result, two floating point numbers will not reliably be equal unless they have been computed by the same algorithm, and not always even then.

**Comment by mllg** [comment]
NB: assertIntegerish should round instead of floor.

**Comment by mllg** [comment]
See commit above, should be fixed now.
