### ISSUE TITLE
C version of qassert doesn't really work with Rcpp

### ISSUE THREAD

**Issue by mattfidler** [mllg/checkmate#180]
This is because the default is to use `Rf_error` to signal errors.  This causes a longjump and is unsafe with Rcpp;  Could you provide a `C++` capable interface by returning the error in some way?

**Comment by mllg** [comment]
I could return a SEXP: TRUE/LogicalVector(1) if everything is fine or a StringVector(1) with the error message.

Would this help?

**Comment by mattfidler** [comment]
Yes. If you do this I will add a pull request of how to use this with Rcpp.  It won't add the Rcpp dependency but would be in the header.  Is that OK?

**Comment by mllg** [comment]
> Yes. If you do this I will add a pull request of how to use this with Rcpp. It won't add the Rcpp dependency but would be in the header. Is that OK?

Not sure if I understand this. In which header?

**Comment by mattfidler** [comment]
> which header?
`checkmate.h`

In there a simple directive of 
```c
#if defined(__cplusplus)
#else
#endif
```
would allow `qassert` to work safely with `Rcpp` and `C` code using the same interface.

**Comment by mattfidler** [comment]
Well, looking at your code, it would be in `checkmate_stub.c` instead of the header.

**Comment by mllg** [comment]
Would #183 work for you?

**Comment by mattfidler** [comment]
Yes.  Let me know when it arrives on CRAN so I can take out my hack :)
