### ISSUE TITLE
assert(combine = "and") gives wrong variable name

### ISSUE THREAD

**Issue by mb706** [mllg/checkmate#182]
```r
> f <- function(a, b) assert(checkFunction(a), checkNumeric(b), combine = "and")
> f(identity, "a")
Error: Assertion on 'a' failed. Must be of type 'numeric', not 'character'.
```
The expected error message would refer to variable `b`.

**Comment by tdeenes** [comment]
@mllg 
This seems to be indeed a bug:
` .var.name = as.character(dots[[1L]])[2L]` should be ` .var.name = as.character(dots[[i]])[2L]` [here](https://github.com/mllg/checkmate/blob/a061f34a79a50f2c8d3f4f3efd8394f5efef76e2/R/assert.R#L54)

**Comment by mllg** [comment]
Indeed, thanks for reporting, and thanks for confirming!
