### ISSUE TITLE
Feature request: add a "not" argument

### ISSUE THREAD

**Issue by DanChaltiel** [mllg/checkmate#193]
Hi Michel, 

When writing tests, I frequently find myself using `stopifnot` instead of `checkmate` when I have to negate some expectations.

For instance, I often want to check some inequalities of value or class. Instead of redefining functions, like `expect_different` or `expect_is_not`, which would indeed be tedious and cumbersome, I wondered if it wasn't possible to have a `not` argument, inherited from `expect` to all its heir.

Here is some dummy example code:

```
a <- 10
expect_equal(a, 10)
expect_equal(a, 11, not=TRUE)
expect_is(a, "numeric")
expect_is(a, "character", not=TRUE)
```

I would personally find this very handy!

**Comment by mllg** [comment]
Checking that something is not "character" or not a specific value is usually not a good assertion or a good unit test. I'd rather encourage writing down the expected return value as precise as possible.
