### ISSUE TITLE
various `checkXYZ` functions permit `list()` ... should they?

### ISSUE THREAD

**Issue by mmuurr** [mllg/checkmate#200]
Example:
```R
checkmate::checkCharacter(list())  ## returns TRUE
```
Since `is.character(list())` is `FALSE`, I'd expect the check above to return `FALSE`, too.

I can easily add a `checkAtomic` check if needed, so I'm not really asking for any change, just curious about the logic. In fact, the current behavior makes one particular check _easier_: checking for decoded string arrays from `jsonlite`, since `[]` decodes to `list()`. (Perhaps that's exactly the type of example that motivated the current behavior?)

checmkate version 2.0.0.

**Comment by tdeenes** [comment]
See #174. Fixed in the devel version.
