### ISSUE TITLE
argument fixed being not a logical mislead me

### ISSUE THREAD

**Issue by SamGG** [mllg/checkmate#206]
Hi,
I have just started using checkmate, which is incredibly concise.
I was mislead by the `fixed` argument which is a string in checkmate whereas it is a logical in standard.
I am wondering if you could consider that when fixed is a logical the searched pattern is pattern not fixed. I think this would change slightly the order of the blocks at https://github.com/mllg/checkmate/blob/434a2cf36020c4fd8eac37b5c50b77e7e28822cc/R/checkCharacter.R#L34-L50
Best,
Samuel

**Comment by mllg** [comment]
You are right, this is misleading if you are used to `grep()`. Unfortunately, changing the API after release is really difficult without breaking packages. You should get an informative error message, though.
