### ISSUE TITLE
CRAN release of version 2.1.0

### ISSUE THREAD

**Issue by FrauH0lle** [mllg/checkmate#213]
I would like to ask if a new release on CRAN for the aforementioned version is planned in the near future.

We are working on a package which is heavily using `checkmate`, specifically the new feature from 2.1.0

> Function assert() now supports collecting assertions via AssertCollection (#112).

Thanks a lot for your work!

**Comment by mllg** [comment]
Recent changes to error message have broken some packages on CRAN, and I'm currently waiting for the maintainers to fix them. There will be a new release in October.
