### ISSUE TITLE
testString - add case for charFrac

### ISSUE THREAD

**Issue by iembry** [mllg/checkmate#217]
Hi, for your testString function, will you also include character fractions to return TRUE for being a string?

Please see the example below:

```
xx <- as.character(fractional::fractional(1:9 / 12))

# > xx
# [1] 1/12 1/6  1/4  1/3  5/12 1/2  7/12 2/3  3/4

# > str(xx)
# 'charFrac' chr [1:9] "1/12" "1/6" "1/4" "1/3" "5/12" "1/2" "7/12" "2/3" ...

# > checkmate::testString(xx)
# [1] FALSE
```

Thank you in advance.

**Comment by tdeenes** [comment]
@iembry you want to use `testCharacter`, and not `testString`. `testString` tests if the input is a **single**-element character vector, so the result you get is expected (and correct).

**Comment by mllg** [comment]
The naming here is confusing, but in this case, that's base R's fault, not mine.

**Comment by iembry** [comment]
@tdeenes  Thank you for letting me know. I will change it to `testCharacter`.
