### ISSUE TITLE
Bug? `test_integerish(Sys.Date())` returns `TRUE`

### ISSUE THREAD

**Issue by tdeenes** [mllg/checkmate#223]
I think this is a similar issue to #164 and maybe qualifies as a bug.

In this line: https://github.com/mllg/checkmate/blob/5e35f452229b2a37536a4e21e1a6b6763fa45dc3/src/integerish.c#L61 it is only checked if the input inherits from "factor".

**Comment by mllg** [comment]
Thanks, now checking for `Date` and `POSIXt`.

**Comment by lucasxteixeira** [comment]
I think this also happens in `test_numeric`: `test_integerish(Sys.Date())`
