### ISSUE TITLE
Typo in `typed.missing` param documentation

### ISSUE THREAD

**Issue by dhersz** [mllg/checkmate#224]
Hi. Apparently there's a small typo in `typed.missing` documentation. I think line 5 (below) should read "Set to **`TRUE`** to enable strict type checking".

https://github.com/mllg/checkmate/blob/e3eaaf07341743951e336c54c71f66c16d007ea0/man-roxygen/typed.missing.R#L1-L5

**Comment by mllg** [comment]
Thanks, fixed now in main.
