### ISSUE TITLE
[Feature requrest] `assertBool`

### ISSUE THREAD

**Issue by schalkdaniel** [mllg/checkmate#239]
I was looking for a function like `assertBool(x)` which basically does the same as `assertLogical(x, len = 1)`. As far as I understand, there are such pendants for `assertNumber(x)` and `assertString(x)` which is basically `assertNumeric(x, len = 1)` and `assertCharacter(x, len = 1)`. 

Would that be something worth adding?

**Comment by tdeenes** [comment]
See assertFlag
