### ISSUE TITLE
sorted option not enforced when sort violations bridge NA

### ISSUE THREAD

**Issue by bifouba** [mllg/checkmate#258]
This fails as expected:
`checkmate::check_integerish(c(2, 1), sorted = TRUE)`

The mere presence of NAs is not an issue, as these continue to fail as expected:
`checkmate::check_integerish(c(2, 1, NA), sorted = TRUE)`
`checkmate::check_integerish(c(NA, 2, 1), sorted = TRUE)`

BUT if the sort order violation is interrupted by NA, it remains unnoticed. 
The following incorrectly returns TRUE:
`checkmate::check_integerish(c(2, NA, 1), sorted = TRUE)`

**Comment by tdeenes** [comment]
@mllg This is a bug in [`is_sorted_double`](https://github.com/mllg/checkmate/blob/aaaa16d38de39d8c38f2fb0d0f92842a612e14b2/src/is_sorted.c#L37). I will prepare a PR in a minute.

**Comment by tdeenes** [comment]
fixed in [PR](https://github.com/mllg/checkmate/pull/259)
