### ISSUE TITLE
checkNamed should allow explicit names as option

### ISSUE THREAD

**Issue by berndbischl** [mllg/checkmate#35]
In quite a few cases I know the names I would like to check for. 
I should be allowed to pass them.

Note that one might want to check for them to be in the order that they are passed, or not in that order (so one check would use == , the other setequal).

IMHO you only need to check that EXACTLY these names occur, not subsets or whatever.

**Comment by mllg** [comment]
This is possible now (but still experimental); I'm not sure if I like the interface.

```{r}
x = setNames(1:3, letters[1:3])
assertNumeric(x, names = .in(letters))
assertNumeric(x, names = .setequal(letters[3:1]))
assertNumeric(x, names = .equal(letters[1:3]))
```

**Comment by berndbischl** [comment]
i would rather not create function with names like .in and .equal. 
there are just too many ways this can clash with other stuff. 

yes, looks nice and fancy and readable on first glance. on 2nd glance: not so much.
if this refers to a check of names, like the docs currently say, make this fact explicit in the naming of the function and remove the possibility of a clash.

**Comment by mllg** [comment]
`checkNames()` is around for a while now. Seems to be flexible enough.
