### ISSUE TITLE
checkNumber(TRUE) returns TRUE

### ISSUE THREAD

**Issue by chrisisback** [mllg/checkmate#37]
Is this the intended behavior?
In addition,
`qassert(TRUE,"i")` and `qassert(TRUE, "I")` throw an error.
`qassert(TRUE, "n")` throws no error, but `qassert(TRUE, "N")` does.

**Comment by piatek** [comment]
* Those two seem to suffer from the same problem:
```
> checkCount(TRUE)
[1] TRUE
> checkNumeric(TRUE)
[1] TRUE
```

* From your previous comments, I understand that the following has the intended behavior:
```
> checkInt(TRUE)
[1] TRUE
```
However, how to check that an argument is an integerish and not a logical?`checkInteger` would allow that, but it would require the user to pass the argument explicitly as an integer:
```
> checkInteger(1)
[1] "Must be of type 'integer', not 'double'"
```

Thanks!

**Comment by mllg** [comment]
With e60ca384addc71aff10dc718f0537eb4a8849539 logicals are not allowed anymore in int, number, count, numeric or integer.
