### ISSUE TITLE
assertClass should output wrong class

### ISSUE THREAD

**Issue by berndbischl** [mllg/checkmate#41]
We currently see something like this:
>  Assertion on 'learner' failed: Must have class 'Learner'

It would be more informative for the user if the wrong class is shown as well.

**Comment by berndbischl** [comment]
Doing it now.

**Comment by berndbischl** [comment]
OK, I decided to print out all classes in case of an error. I also do not see performance losses.

As we call this function 100000 times: Can you please carefully recheck my code and test change and close if you think it is OK?

**Comment by mllg** [comment]
You forgot to push?

**Comment by berndbischl** [comment]
Sorry, phone

**Comment by berndbischl** [comment]
Updating rox2, then push

**Comment by berndbischl** [comment]
Ok done please check
