### ISSUE TITLE
parameter null.ok

### ISSUE THREAD

**Issue by jakobbossek** [mllg/checkmate#43]
Hi,

quite often we check some argument only if it is not `NULL`, but `NULL` is allowed too. This leads to a bunch of check of the following type, which bloat the code and make it less readable:
```splus
if (!is.null(param)) {
  assertNumber(param, na.ok = FALSE, lower = 1)
}
```
I think the the introduction of another parameter `null.ok` with default value `FALSE` would be great!
```splus
  assertNumber(param, na.ok = FALSE, null.ok = TRUE, lower = 1)
```

What is your opinion?

**Comment by berndbischl** [comment]
I can understand why you want that we discussed this here, buried in #7.

I can also understand why mllg then decided against this.
It is a somewhat ugly special case.

**Comment by jakobbossek** [comment]
Ok, reading the referenced issue and the corresponding discussion I can understand mllg's point of view as well. Closing this.
