### ISSUE TITLE
checkDataFrame in tutorial?

### ISSUE THREAD

**Issue by aydindemircioglu** [mllg/checkmate#50]
in the example for checkDataFrame we have

testDataFrame(iris, "data.frame")
testDataFrame(iris, "data.frame", min.rows = 1, col.names = "named")

but this should be actually

testDataFrame(iris)
testDataFrame(iris, min.rows = 1, col.names = "named")

as the first ones gives me "FALSE" back?

**Comment by aydindemircioglu** [comment]
and if possible, add a hint that to check for specific columns (e.g. if iris has a column named Species) can be done via testSubset, hopefully this minimizes searching.

**Comment by mllg** [comment]
I've fixed the broken example and added some notes pointing to `checkSubset`.
