### ISSUE TITLE
checkInt with na.ok = TRUE and boundary: bug or feature?

### ISSUE THREAD

**Issue by surmann** [mllg/checkmate#51]
Hallo!

I check a variable for natural values or `NA` with the following code:
```R
n = NA
checkInt(n, na.ok = TRUE, lower = 1L)
```
which throws the error:
```
Error in checkInt(n, na.ok = TRUE, lower = 1L) : 
  Bound checks only possible for numeric variables
```
Is this a bug or a feature?
I use `checkmate` version 1.6.0.

**Comment by mllg** [comment]
The result is ok in my opinion, but the message is misleading. Will fix this soon.

**Comment by berndbischl** [comment]
Shouldnt this simply pass?

**Comment by berndbischl** [comment]
IMHO this should just pass without error. The semantics should be scalar int >= 1 OR an NA.

**Comment by mllg** [comment]
Ah, right. Needs some restructuring in the C code.

**Comment by mllg** [comment]
Should be fixed. Will update on CRAN in 1-2 weeks.
