### ISSUE TITLE
package needs to require later version of R

### ISSUE THREAD

**Issue by larskotthoff** [mllg/checkmate#55]
The `checkDirectory()` function uses `dir.exists()`, which was only introduced in R 3.2.0. DESCRIPTION should be updated to reflect this; at the moment it requires R > 3.0.0.

**Comment by berndbischl** [comment]
We had some problems due to this before, but michel claimed he had some code in there to handle this

**Comment by berndbischl** [comment]
and forcing a hard dependency on 3.2 does not seem good

**Comment by larskotthoff** [comment]
Well GH master doesn't work for me on R 3.0.2.

**Comment by berndbischl** [comment]
Why does that that now work?
https://github.com/mllg/checkmate/blob/master/R/backports.r

**Comment by larskotthoff** [comment]
Hmm, don't know. I got an error that `dir.exists` isn't defined.

**Comment by berndbischl** [comment]
Can you please check these lines "manually" in your R?
We had a similar report before and I dont know what is wrong

**Comment by larskotthoff** [comment]
Ah, as it turns out there are different R versions installed on the cluster nodes I was running this on. The package was built with R 3.2 and run with R 3.0...
