### ISSUE TITLE
Reduce .Call overhead

### ISSUE THREAD

**Issue by hadley** [mllg/checkmate#57]
Currently you have:

```R
anyNaN = function(x) {
  .Call("c_any_nan", x, PACKAGE = "checkmate")
}
```

You can reduce the .Call overhead by directly registering the endpoint:

```R
#' @useDynLib checkmate c_any_nan
anyNaN = function(x) {
  .Call(c_any_nan, x)
}
```

It's not as faster as a primitive function, but it's quite a bit faster

**Comment by mllg** [comment]
Thanks!

**Comment by hadley** [comment]
You might also want to recheck the text in the speed part of the vignette - for fast functions, this reduction in overhead might change the graphs a bit.
