### ISSUE TITLE
checkString doesn't allow to check for empty string, lacks min.chars parameter

### ISSUE THREAD

**Issue by UweBlock** [mllg/checkmate#59]
I'm trying to use assertions in all functions. So, easy coding and readability is key. Currently I'm trying `checkmate` out in a project.
I was surprised to learn that `checkString()` doesn't allow for checking for an empty string
```
> checkmate::checkString("")
[1] TRUE
```
I had to resort to the vector version
```
> checkmate::checkCharacter("", any.missing = FALSE, len = 1L, min.chars = 1L)
[1] "All elements must have at least 1 characters"
```
which is cumbersome and the error message is distracting.
Adding a `min.chars` parameter to `checkString()` would solve my issue and also would enhance functionality in general.
Thank you for considering this,
Uwe

**Comment by mllg** [comment]
I want to keep the scalar versions simple, so I opted for the argument `empty.ok` (see 9eadcbf345871e3768f89561110fb5259df40e2f) to trigger a check of type `nchar(x) >= 1`. If this is not sufficient for you, please let me know.

**Comment by UweBlock** [comment]
Sensible argument. `empty.ok` is fine for me. Thank you very much.

**Comment by UweBlock** [comment]
Works like a charm.
