### ISSUE TITLE
Best practice to check `Date` and `POSIXct` efficiently?

### ISSUE THREAD

**Issue by UweBlock** [mllg/checkmate#60]
I'm working a lot with data of class `Date` and `POSIXct` and I wonder if there are more efficient ways to check scalars and vectors of those classes.

My current work around is

```
yesterday <- Sys.Date() - 1   # to be used as upper limit

x <- Sys.Date()   # variable to be checked
str(x)
checkClass(x, "Date")
[1] TRUE
checkIntegerish(x, lower = 0L, upper = yesterday)
[1] "All elements must be <= 16835"

y <- Sys.time()   # variable to be checked
str(y)
checkClass(y, "POSIXct")
[1] TRUE
checkIntegerish(y, lower = 0L, upper = as.POSIXct(yesterday))
[1] "All elements must be <= 1.45454e+09"
```

The checks are working but the error message isn't very helpful.

Any ideas, please?

**Comment by mllg** [comment]
Something like this?

```r
checkDate = function(x, lower = NULL, upper = NULL) {
  if (inherits(x, "POSIXlt")) {
    x = as.Date(x)
  } else if (!inherits(x, "Date")) {
    return("Must be of class 'Date'")
  }

  if (!is.null(lower)) {
    lower = as.Date(lower, origin = "1970-01-01")
    if (any(x < lower))
      return(sprintf("Date must be >= %s", lower))
  }

  if (!is.null(upper)) {
    upper = as.Date(upper, origin = "1970-01-01")
    if (any(x > upper))
      return(sprintf("Date must be <= %s", upper))
  }

  return(TRUE)
}

```

**Comment by mllg** [comment]
I've added `checkDate` in ea95f6104c0f51434199706c65fc74ea04c92b1b. Please give me some feedback if you are missing functionality or if you think that it the implementation is inconvenient etc.

**Comment by jackwasey** [comment]
I haven't had a chance to use this yet, but I think you're opening a can of
worms, especially with date range things which will definitely give some
users time zone problems. The whole r problem with date and date time being
different things is only the beginning of it. I would stick to simple
validation of type. The whole package lubridate tries to overcome these
difficulties, so I'd recommend either (optionally, with requireNamespace as
needed, not import) using lubridate, or sticking to type validation only.
I'd favor just type validation. Thanks for your work.

**Comment by mllg** [comment]
Thanks for sharing your concerns. I think you are basically right. Dealing with DateTime classes is not very straightforward. I've simplified `checkDate` to only accept `Date` objects which are as far as I know well defined without a timezone.

**Comment by jackwasey** [comment]
I saw the POSIXlt and panicked. Ultimately, the user has to deal with all the time zone problems, but particularly in a package such as yours, designed to tighten up function input, the user may be falsely reassured. I don't see any time zone related tests. Why not just stick with Date, and ignore POSIXlt and POSIXct? Of course it is possible to cast to Date, but I still think it is a can of worms. The other thing I'd add is that I love the checkmate package because of the C speed, so having a brief R implementation of a very complex issue, for me, seems to deviate from the mission. Thanks again or your work.

**Comment by UweBlock** [comment]
@mllg Your response to my question is highly appreciated. 
Though, I'm afraid my second example with POSIXct was ill casted and misleading. I consider Date, POSIXct, POSIXlt as different data types when passed to functions. Here, I'm following your advice for clean function interfaces. I have updated the second example accordingly.

@jackwasey I agree, time zones are crucial. And also Date is using time zones.

Probably, my examples were too simplistic. Need a second thought.

**Comment by eddelbuettel** [comment]
Gentlemen,

I would like to, if possibly, reopen this.  Just like Uwe, I work a lot with both `Date` and `POSIXct`.  And we learned the hard way over the years to not willy-nilly convert.  So while checks for `Date` are in `checkmate`, I am wondering what to do about `POSIXct`.   I am seeing a use case for `anytime()` to basically convert + ensure on entry, but it would also be nice to "assert" the type properly.  So I am currently shopping for an assertion package.   Could we add `POSIXct` tests there?   (Internally this is just a `double` with an attribute as you all know.)

And for the record, `Date` tends not to have a timezone.  TZ attribute tend to enter `POSIXlt` and `POSIXct` but there are a million ways to loose them.   

But I am dealing with "legacy code" where we have chars like "20171006 160102" and those are worse.

**Comment by mllg** [comment]
I can look into it next week. What kind of attributes/properties do you need to test?

**Comment by eddelbuettel** [comment]
I played with a little (based on your existing `checkDate`) at work before leaving.  Mostly "is", ie not NA.
Within range is trickier and gets us to TZ issues. A first simplification would be to do all ranges at UTC and ignore TZ.

**Comment by eddelbuettel** [comment]
Pulled and installed, will hope to have a to poke on the train or at home.  `?checkPOSIXct` looks good.

**Comment by eddelbuettel** [comment]
Didn't have time yet to do anything extensive --- but this looks like pretty much what was needed.  

I think we can close this once merged, or now if you prefer.

**Comment by mllg** [comment]
Merged now. I've additionally added the argument `sorted`.
