### ISSUE TITLE
No default argument for .var.name

### ISSUE THREAD

**Issue by drknexus** [mllg/checkmate#61]
This is a stylistic issue, and so may not be considered an issue at all, but I thought I'd mention it.  .var.name in the assert family of functions has no default argument.  This doesn't cause a problem in function execution, just a problem with syntax validation (as RStudio does it).  RStudio syntax checking isn't flawless, but it has been useful on occasion to find issues, and it is helpful if otherwise well behaving code doesn't generate warnings.

Otherwise, great package! Thanks for making it available.

**Comment by mllg** [comment]
So RStudio's linter gives you false positives if the function correctly handles missingness? "Not flawless" seem to be an exaggeration in this case :wink:
 
Would changing the default to `NULL` would solve this?

**Comment by tdeenes** [comment]
+1 for this option (.var.name = NULL as default).

**Comment by jackwasey** [comment]
+1, although it is really an RStudio bug.

**Comment by mllg** [comment]
Should be fixed in cd87d4a71b0c9a5b09131f4274e9dc7da0bdafd5. Thanks for the suggestion.
