### ISSUE TITLE
`match.arg` similar method

### ISSUE THREAD

**Issue by nutterb** [mllg/checkmate#66]
Good news.  I just rewrote one of my functions using `checkmate` and it contributed to cutting down the run time by half :+1: 

But since no good deed goes unpunished, the one thing I have found that I don't have in `checkmate` is something similar to the `base::match.arg` function.  `checkChoice` and `checkSubset` come close, but neither of them support partial matching, and neither return the value of the matched argument.  And while it seems like it would be natural to just use `match.arg`, I would miss the pleasure of including it in an `AssertCollection` (in most cases, I find I don't really need the actual value of the argument until after I've conducted all of my checks).

How is this as a starting point?

```r
assert_match_arg <- function(x, choices, several_ok = FALSE, ...)
{
  x <- choices[pmatch(x, choices, nomatch = 0L, duplicates.ok = several_ok)]
  if (several_ok) assertSubset(x, choices, ...)
  else assertChoice(x, choices, ...)
  x
}

assert_match_arg("p", c("pearson", "kendall", "spearman"),
                 .var.name = "method")

assert_match_arg(c("p", "k"), c("pearson", "kendall", "spearman"),
                 .var.name = "method")

assert_match_arg(c("p", "k"), c("pearson", "kendall", "spearman"),
                 .var.name = "method", 
                 several_ok = TRUE)

assert_match_arg("q", c("pearson", "kendall", "spearman"), 
                 .var.name = "method")

coll <- makeAssertCollection()
assert_match_arg("q", c("pearson", "kendall", "spearman"),
                 .var.name = "method",
                 add = coll)

reportAssertions(coll)
```

**Comment by mllg** [comment]
Does 3c29184ae2e604d795febe213aad9d0338e855f7 help?

In comparison to your version, unmatched elements of `x` will not be ignored. I.e., this did not throw an error (but should do, right?):
```r
assert_match_arg(c("p", "q"), c("pearson", "kendall", "spearman"))
```

**Comment by nutterb** [comment]
You're about to discover that I've put way too much thought into this since I first posted the request.  Sorry about the length.

I'm not sure adding an option for partial matching in `checkChoice` and `checkSubset` helps.  And I'm not crazy about the idea of partial matching in `checkChoice` and `checkSubset`, even if it is optional.  Finding a match against `"p"` and later comparing against `"pearson"` is bound lead to trouble.  This kind of partial match discrepancy is precisely what `match.arg` is trying to avoid.

The oddity of `match.arg` is that it returns a `character(1)` (or character vector, if `several.ok = TRUE`) if a match is found, but throws an error if it can't resolve a match.  In other words, it's return type is inconsistent.  `checkChoice` and `checkSubset`, on the other hand, have consistent logical returns, and the assert versions have consistency in either silent resolution, or throwing an error.

With that in mind, I think there's a fair argument to be made that something like `assert_match_arg` as I've described it doesn't fit in `checkmate` because it's structure is inconsistent with the rest of the functions.

An `assert_match_arg` also differs from the rest of `checkmate` in that it doesn't have a natural `check` or `test` version.  By it's nature, `match.arg` is an assertion, and if you were to attempt to turn it into a `check` form, you'd get either `checkChoice` or `checkSubset`. I find myself admitting that `assert_match_arg` is kind of redundant in that regard.

So the question is really, why bother making such a function?  My answer is that `checkChoice` and `checkSubset` don't return the character values when successful, they return logicals.  And so I can't use them to turn a partial match into a full match I may need later on. Well, I can, but it requires additional code, and I'd like to be able to do it in one line.  So I write `assert_match_arg` as that additional code.

Given that `assert_match_arg` is so very different from the rest of the `checkmate` philosophy, I'd understand if you weren't keen on including it.  It just seemed like a natural place to propose it since I'm likely to use it in multiple packages.  But I can always make it a gist and copy it into my packages as an unexported function where I need it as well.

For completeness, you were correct that my original attempt did not exactly mimic the behavior of `match.arg`.  I've spend a little more time working through the different scenarios, and I think I've got a good match now (below).  

I've also included examples of each case for comparison.

```r
assert_match_arg <- function(x, choices, several_ok = FALSE, 
                             .var.name = vname(x), add = NULL)
{
  if (identical(x, choices))
    if (several_ok) return(x) else return(x[1])

  if (!several_ok)
  {
    checkmate::assertCharacter(x, len = 1, 
                               .var.name = .var.name, add = add)
    #* If an AssertCollection is used, we want to mimic a failure
    #* to find a match.
    return(character(0))
  }
  
  x <- choices[pmatch(x, choices, nomatch = 0L, duplicates.ok = several_ok)]
  if (several_ok) checkmate::assertSubset(x, choices, empty.ok = FALSE, 
                                          .var.name = .var.name, add = add)
  else checkmate::assertChoice(x, choices, 
                               .var.name = .var.name, add = add)
  #* If a match(es) is found, return it.  If no match is found
  #* and an AssertCollection is used, return character(0)
  x
}

#* Pass in default values; several.ok = FALSE
#* Returns character(1)
match.arg(arg = c("pearson", "kendall", "spearman"),
          choices = c("pearson", "kendall", "spearman"))

assert_match_arg(x = c("pearson", "kendall", "spearman"),
                 choices = c("pearson", "kendall", "spearman"))

#* Pass in default values; several.ok = TRUE
match.arg(arg = c("pearson", "kendall", "spearman"),
          choices = c("pearson", "kendall", "spearman"),
          several.ok = TRUE)

assert_match_arg(x = c("pearson", "kendall", "spearman"),
                 choices = c("pearson", "kendall", "spearman"),
                 several_ok = TRUE)

#* Pass in a valid character vector; several.ok = FALSE;
#* returns error, `arg` must be of length 1
match.arg(arg = c("p", "k"),
          choices = c("pearson", "kendall", "spearman"))

assert_match_arg(x = c("p", "k"),
                 choices = c("pearson", "kendall", "spearman"))

#* Pass in valid character vector; several.ok = TRUE
#* Returns a character vector
match.arg(arg = c("p", "k"),
          choices = c("pearson", "kendall", "spearman"),
          several.ok = TRUE)

assert_match_arg(x = c("p", "k"),
                 choices = c("pearson", "kendall", "spearman"),
                 several_ok = TRUE)

#* Pass in invalid character vector; several.ok = FALSE;
#* Returns error
match.arg(arg = c("p", "q"),
          choices = c("pearson", "kendall", "spearman"))

assert_match_arg(x = c("p", "q"),
                 choices = c("pearson", "kendall", "spearman"))

#* Pass in invalid character vector; several.ok = TRUE;
#* Returns error
match.arg(arg = c("p", "q"),
          choices = c("pearson", "kendall", "spearman"),
          several.ok = TRUE)

assert_match_arg(x = c("p", "q"),
                 choices = c("pearson", "kendall", "spearman"),
                 several_ok = TRUE)
```

**Comment by mllg** [comment]
I've removed the partial matching in `*Subset` and `*Choice` again and implemented `match_arg`/`matchArg` similar to your implementation: d638a7cfaf9cb3c293b21c1b500da9cbf9b71f2e. Please let me know if `match_arg` suits your needs.

**Comment by nutterb** [comment]
Sorry it took me so long to take a look at this.  I can definitely work with this implementation.  Thanks for working it up.
