### ISSUE TITLE
name clash test_file

### ISSUE THREAD

**Issue by berndbischl** [mllg/checkmate#67]
it is probably not a good idea, especially as the package is also meant as a companion to testthat, to mask function testthat::test_file with another one.

**Comment by berndbischl** [comment]
you still export test_file, your fix did not close this. you still mask this from testhat

**Comment by mllg** [comment]
Yep, the all packages need to switch to `*FileExists` and `*DirectoryExists` before I can unexport the function.

**Comment by mllg** [comment]
https://github.com/jakobbossek/netgen/pull/39
https://github.com/berndbischl/tspmeta/pull/2

https://github.com/mlr-org/farff/commit/a8c22b893bb9e23f90ca4955486719192f7c93e4
https://github.com/mllg/batchtools/commit/8366708f6df71883fedc79cf06013794b2e13e99
https://github.com/tudo-r/BatchJobs/commit/e6c01b07425bcbaa283bbfc1e30f252efcff4868
https://github.com/berndbischl/BBmisc/commit/46e0cfbd142deb13496f2736466ce0852d14978f
https://github.com/berndbischl/parallelMap/commit/c47adb03138d97154c5ad51be870ea20683ddb71
https://github.com/mllg/fail/commit/1162bfe2993b432cfcd3230286a16826c30849db
https://github.com/openml/openml-r/commit/f4683089a7442afdb7bb1476fc7d1fdab55f7b41

**Comment by berndbischl** [comment]
> Yep, all packages need to switch to *FileExists and *DirectoryExists before I can unexport the function.

ah fuck, i did not check whether test_file was already in "heavy use". is this doable at all?

**Comment by mllg** [comment]
This is not urgent. Everything still works and I've removed `test_file` from the devel version of checkmate (v1.8.1) so that there are no more name clashes. Luckily, `test_file` was not used in any CRAN package.

Nevertheless, I want let these inconsistency fade out for future versions.

**Comment by berndbischl** [comment]
Agree to all points and thx.

**Comment by mllg** [comment]
`test_file` is not longer exported in the current CRAN version.
