### ISSUE TITLE
Is assertFunction("min") expected to pass?

### ISSUE THREAD

**Issue by jakob-r** [mllg/checkmate#71]
It passes at the moment.

**Comment by berndbischl** [comment]
as the internal code calls match.fun on x, apparently "yes".

but this is undocumented. so at least a bug in docs.

i personally would probably also not wanna do the string matching in general....
but there is no flag to disable this.

**Comment by jakob-r** [comment]
Isn't this rather drastic. Why not have both?

**Comment by mllg** [comment]
Do you have a use case where passing a function as string is necessary?

**Comment by berndbischl** [comment]
> Do you have a use case where passing a function as string is necessary?

I usually don't. Also the user can manually in that case call match.fun? That errmsg (if a wrong string is used) seems pretty informative to me. 

I dont see this as urgent, but if one wants to be very convenient, you could see this as analogues to asInt and write it like this:

``` 
f = assertFunction("foo", match.fun = TRUE) # inconsistent with asInt
f = asFunction("foo") #  more consistent with asInt 
```
