### ISSUE TITLE
Asserting an arg that accepts multiple classes with OR

### ISSUE THREAD

**Issue by MasonGallo** [mllg/checkmate#72]
I am writing a function that can accept class1 OR class2. Looking at the documentation for `assertClass`, the examples only show AND functionality. 

@berndbischl mentioned this is doable just using `assert`. Perhaps an example in the vignette or documentation would be helpful for others in the same situation?

**Comment by berndbischl** [comment]
I added this for @mllg 

@MasonGallo 
But I dont see your problem with the examples of ?assert.
This has this and seems ok for me?
#' assert(checkChoice(x, c("a", "b")), checkDataFrame(x))

**Comment by MasonGallo** [comment]
@berndbischl 
Yes this is true, but the user needs to know that assert is appropriate for this case in the first place to go there. That's why I would suggest either a quick mention/ex in the vignette (for the first time user like me) or mention for the example in ?assertClass that OR is available via assert since AND is mentioned.

**Comment by berndbischl** [comment]
as you can see, i did that for the vignette in the linked PR.

i will add now another example for ?assertClass in the PR, i guess you are right that this is a good place

**Comment by MasonGallo** [comment]
Oh geez, I did not notice your PR until now. I think that will definitely help new users.

**Comment by berndbischl** [comment]
> i will add now another example for ?assertClass in the PR, i guess you are right that this is a good place

done.

**Comment by mllg** [comment]
Can be closed now, right?

**Comment by MasonGallo** [comment]
I think so. Thanks!

**Comment by berndbischl** [comment]
> Can be closed now, right?

sure
