### ISSUE TITLE
Should the as* coercion functions be part of checkmate?

### ISSUE THREAD

**Issue by tdeenes** [mllg/checkmate#77]
@mllg May I suggest to move the coercion functions (`asInteger`, `asCount`, `asInt`) to a separate package? IMHO these functions do not relate at all to the core functionality of the checkmate package, but can cause name clashes with other packages or custom scripts (especially `asInteger`).

**Comment by mllg** [comment]
You are right and I probably will move these functions in the future. However, there is currently no package I know of which causes name clashes. Do you know one?

**Comment by berndbischl** [comment]
note that these functions are in HEAVY use in all what we have.

a few more comments:

1) i really dont see the argument to move this to an extra package. first, what should be in there? like 5 mini functions? also this is IMHO tightly coupled with arg checking. 

2) i have never really liked the naming here as well. asInteger, even if there would be no name clash, is just too confusingly named like as.integer. the function does something else. it foremost does the arg check. but also a conversion as a little nice sideeffect.

3) why not simply use the return value of the assert-function for this? 
k = 1; k = assertInt(k)
you already return the arg.
in teh above code, k is still a double after the assert.
why not convert it to an int? if you dislike this, let the user request the conversion with a flag.
this can also be useful at other places.

and one could then fade out asInteger and other stuff.

**Comment by mllg** [comment]
> 3) why not simply use the return value of the assert-function for this? 
> k = 1; k = assertInt(k)

Its a convention now that the object is returned invisibly to use assert functions in compound statements.

**Comment by berndbischl** [comment]
> Its a convention now that the object is returned invisibly to use assert functions in compound statements.

... and? how answers this the "why not convert it"?

**Comment by tdeenes** [comment]
@mllg I have a non-public package with a whole set of coercion functions, and my package also imports *checkmate*. Of course there are several workarounds to avoid the name clash, but this use case let me think why `asInteger` is needed at all in *checkmate*. The CRAN packages having the same function are *rmngb* and *bigReg* (you can use `utils::RSiteSearch` and `sos::findFn` as a more pleasant alternative to figure this out).

**Comment by tdeenes** [comment]
@mllg @berndbischl 
As for the conversion issue, I agree that a simple flag (e.g., `force_coercion = FALSE`) could be added to those `assert* ` functions where it makes sense to either return the original input or a type-safe version of the input.

**Comment by mllg** [comment]
I've added an coercion argument. Thanks for the discussion.
