### ISSUE TITLE
add "count" as mode to expect_matrix and friends

### ISSUE THREAD

**Issue by maxheld83** [mllg/checkmate#79]
I'm finding myself frequently wanting to check that some matrix (or other datatype) consists only of "mode" (I know it's not a mode) `count` (as opposed to just `integer`), so with `checkCount(x) == TRUE` for all.

Would that be a worthwhile addition, or is there already an elegant way to do this?

Currently, I'm working with a hack-fix like so, with `res` being a matrix of all counts.

```
expect_true(object = all(apply(X = res, MARGIN = c(1,2), FUN = function(x) test_count(x))), info = c("all cells are counts"))
```

**Comment by berndbischl** [comment]
well, for the real mode integer, one can already check.

isnt the missing feature to check for box constraints - as you can check for in vectors?

**Comment by mllg** [comment]
There is a workaround for this specific case because matricies are just vectors with an attribute attached and no class set (!). I'm not sure if it is generally a good idea that `checkInteger` accepts matrices, but for now this works:

```{r}
checkMatrix(x)
checkInteger(x, lower = 0)
# or: checkIntegerish(x, lower = 0)
```

**Comment by mllg** [comment]
I can also add `counts` as a new mode to `checkMatrix` and `checkList`. Sounds like a useful addition.

**Comment by mllg** [comment]
I guess my workaround should be sufficient for most cases and is a clean solution. Let's try to keep the interface slim.
