### ISSUE TITLE
document how to add custom expectations

### ISSUE THREAD

**Issue by maxheld83** [mllg/checkmate#80]
I love this package, and in particular enjoy how the same expectations can be used at run-time (via `checkmate`)  and at build (via `testthat`), which is why I'd love to add custom expectations that can be used in both packages (as `check*`, `test*`, `assert*`).

I haven't been able to come by a lot of documentation on how to do this (even just for `testthat`), aside from [this SO post](http://stackoverflow.com/questions/34085729/how-do-you-test-a-custom-expectation), so if there's any interest in this, I'd love some documentation on how to do this (well / elegantly).

Or is this a bad idea?

(Specifically, I'd want to add expectations about particular kinds of matrices, which should always be compared to some other vector).

**Comment by berndbischl** [comment]
After I have read your post, I have realized that I am already doing the same. 
(but not in a well structured way).

My usecase seems to be most often that I need this for S3-classes in my packages.
So i have something like assertMyClass(....), where i need to check considerably more than just the class with assertClass.

I am too tired to think this through now, but maybe one even wants a generic here?
So I basically implement check.MyClass / assert.MyClass?

**Comment by mllg** [comment]
To extend checkmate, you just have to write a `check*` function, e.g.
```{r}
checkSquareMatrix = function(x, ...) {
  res = checkMatrix(x, ...)
  if (!isTRUE(res))
    return(res)
  if (nrow(x) != ncol(x))
    return("Must be square")
  return(TRUE)
}
```
You can use the functions `makeExpectationFunction` to create an `expect*` function:
```{r}
expect_square_matrix = makeExpectationFunction(checkSquareMatrix)
```
This function is created at **compile-time** if you define it in the namespace of a package, so there is no need to worry about any overhead. Some with `makeAssertionFunction` and `makeTestFunction`.
Does this help?

**Comment by mllg** [comment]
I've also put this into the vignette. Let me know if the docs are still not detailed enough.
