### ISSUE TITLE
add "integerish" mode to expect_matrix and friends

### ISSUE THREAD

**Issue by maxheld83** [mllg/checkmate#81]
I find `integerish` a very helpful concept (though I'm debating whether I should, in fact, force data to integer when that is what they really are).

Could this be added as a mode, too? I see the tension here that this – much like #79 - *wouldn't* be an actual R storage mode, so it's a little confusing and maybe a bad idea.

I'm just adding it here because I ran into it as a user and felt like it would be convenient (though perhaps inconsistent), when testing an entire matrix for being integerish via `expect_matrix()`.

Feel free to close this if it doesn't seem like a good idea to you to expand the `mode` arguments to these non-modes like `integerish` and `count` (#79).

**Comment by mllg** [comment]
Good idea. Added to the package.

**Comment by maxheld83** [comment]
fantastic; I love your package.
