### ISSUE TITLE
assert_true / assert_false

### ISSUE THREAD

**Issue by MansMeg** [mllg/checkmate#85]
Hi!

Thanks for a great package! I use it almost every day! But there is one assertion that I am missing in the package. A assert_true() and assert_false() to do more specific test not covered by the other functions.

**Comment by MansMeg** [comment]
Sorry! Just realized I could just use assert(TRUE). Sorry!

**Comment by mllg** [comment]
You were right, `assert_false` and `assert_true` were missing and seem useful to have. I've added them to the package for checkmate-1.9.0. 

`assert(TRUE)` might give you a funny error message, I don't think that you want to do that.

**Comment by MansMeg** [comment]
No. Ive been using it so far and it is not as nice as the other functions. Ill try out assert_true()/assert_false() now that they are available.  

Thanks again for a extremely good package!
