### ISSUE TITLE
extending checkmate inside package causes problems: undocumented arguments "info", "label" (etc.)

### ISSUE THREAD

**Issue by maxheld83** [mllg/checkmate#89]
Following up on #80 I am extending checkmate with custom `check_()`s for my package, written *in* and exported *by* that package.

I'll start with the example used in the checkmate vignette.

Adding this works just fine, and `R CMD Check` is happy is ever:

```
#' @title test extension
#' @export
#' @description just testing the extension
#' @param x Some matrix
#' @param mode Some mode
checkSquareMatrix = function(x, mode = NULL) {
  # check functions must return TRUE on success
  # and a custom error message otherwise
  res = checkMatrix(x, mode = mode)
  if (!isTRUE(res))
    return(res)
  if (nrow(x) != ncol(x))
    return("Must be square")
  return(TRUE)
}
```

But now I also want to programmatically create the related `expect_()` etc. functions.

So again, I turn to the example, and proceed much as `checkmate` does internally, and add this to my package:

```
#' @export
#' @rdname checkSquareMatrix
expectSquareMatrix <- makeExpectationFunction(checkSquareMatrix)
```

This is where I run into trouble with `R CMD Check`:

```
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'checkSquareMatrix'
  ‘info’ ‘label’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```

That makes sense; my package doesn`t know about `info` and `label`, but I also wouldn't know where to add them.

Any thoughts on how to solve this / do this cleanly?

I am guessing that `#' @include makeAssertion.R` which is called inside `checkmate` has something to do with this problem, but since I don't necessarily have the `checkmate` source available in my package, wouldn't know what to do about it.

**Comment by mllg** [comment]
> Any thoughts on how to solve this / do this cleanly?

I personally would put expect-functions in a helper file in the testthat directory, i.e. in `[pkg]/tests/testthat/helper_checkmate.R`. Or is there a specific reason why they should be (a) in the package and (b) exported to the user?

**Comment by maxheld83** [comment]
I'd like my users to be able to use `expect_squareMatrix()`, `assert_squareMatrix()` and friends in their own scripts, where I expect they'll do their own weird stuff with objects, but might want to make sure that the objects are sound.
Medium term, I (and perhaps other people) may also build on this with other packages, and it would be helpful to have my entire extended `checkmate` family available to the user (just like they are when `library(checkmate)`).
Bottom line: I just want to export all of my extensions so that I never have to think about this again.
Maybe this is a stupid goal, or I'm missing an important point.

Because I couldn't get `makeExpectationFunction` to coexist peacefully with `R CMD Check` (see above) I've now solved the problem like so:

```
#' @export
#' @rdname checkSquareMatrix
#' @inheritParams checkmate::makeExpectation
expectSquareMatrix <- function(x, mode = NULL, info = NULL, label = vname(x)) {
  res <- checkSquareMatrix(x = x, mode = mode)
  makeExpectation(x = x, res = res, info = info, label = label)
}
```

This *works*, but seems inelegant and somewhat error prone (compared to just invoking `makeExpectationFunction()`).

**Comment by maxheld83** [comment]
So, actually, I seem to just be really dense tonight, all I needed was *one* line of the above, just the `@inheritParams checkmate::makeExpectation`, like so:

```
#' @export
#' @rdname checkSquareMatrix
#' @inheritParams checkmate::makeExpectation
expectSquareMatrix <- makeExpectationFunction(check.fun = checkSquareMatrix)
```

That appeases `R CMD Check` because then it has some docs on `mode` and `info`.

I'm leaving above convoluted code as a memorial to my own denseness (density?).

Really love this package!

**Comment by mllg** [comment]
Glad you figured this out.
