### ISSUE TITLE
how to pass several `x`s (and with different names) to `makeAssertion()` and friends

### ISSUE THREAD

**Issue by maxheld83** [mllg/checkmate#90]
(Following up on #80 as well), I am adding some custom `check_()s` to my package, including a lot of checks with *several* inputs, whose *consistency* is being checked.
Those custom `check_()s` are similar to [`checkSubset()`](https://mllg.github.io/checkmate/reference/checkSubset.html) which has `x` *and* `choices` arguments.
I sometimes have two or three such arguments, and I find it important to give them meaningful names (*other* than `x`, just like `choices` isn't called `y`).

Setting up a `check_()` works just fine, and I have it return `TRUE` or a string, as expected. 

However, the custom `check_()` with such non-`x`-arguments doesn't seem to sit well with `makeAssertion()` and its friends.

From the checkmate docs:

```
assertFalse = function(x, .var.name = vname(x), add = NULL) {
  res = checkFalse(x)
  makeAssertion(x, res, .var.name, add)
}
```

I'm not sure at all how I could pass my arguments on to `makeAssertion` since it seems to require only one called `x`.

Is there a good / elegant way to extend checkmate for my use case?

Ps.: I could of course just pass the different arguments for consistency check as a *list* `x` (as in: `x = list(arg_a = arg_a, arg_b = arg_b)`) but that might screw up my design and be bad for the user.
Again, I'm trying to model my stuff on `check_subset()`.

**Comment by mllg** [comment]
I'm not 100% sure that I understand your use case.

If the properties/attributes of object `x` are described by additional arguments (like `choices`, `min.len` etc.), any deviation should be represented in the string `res` which is then passed to `makeAssertion`.

If you have multiple objects which are related, you might consider to give the compound of these objects a class.

There are corner cases, e.g. something like `checkSameDimension(x, y, z)`. Here, it is important to note that `x` is basically not used in `makeAssertion` and mostly used to retrieve the variable name from the parent frame. In these cases you can usually just "overwrite" the `var.name` to create a custom error message.

Does that help?

**Comment by maxheld83** [comment]
Yes, that helps a lot, thanks so much.
I think I now have a clearer understanding of what I was running up against here, described in more general terms in #95 

Therefore closing this.
