### ISSUE TITLE
more information on argument documentation convention [logical(1)] and friends

### ISSUE THREAD

**Issue by maxheld83** [mllg/checkmate#91]
I really like the way you succinctly document the kind of input an argument requires.

Your `code{[logical(1)]}` seems a lot less verbose than the usual `a logical vector of length 1`.

How did you come up with this? Is this convention documented / recommended somewhere?

I'm wondering how, for example, to document the expectation of a numerical array for an argument.

Love this package and the way it is carefully built and documented (with `pkgdown()` and all the other best practices).

**Comment by berndbischl** [comment]
> I really like the way you succinctly document the kind of input an argument requires.
> 
> Your code{[logical(1)]} seems a lot less verbose than the usual a logical vector of length 1.

well we defined this (for many projects) simply to be precise when it comes to types.
i wrote this down in a style guide some years ago, was surprised that no "standard" existed in R for this (as always)

https://github.com/rdatsci/PackagesInfo/wiki/R-Style-Guide

**Comment by maxheld83** [comment]
ah fantastic, thanks for the resource, that's what I had hoped.

So how would you document, say, an expected integer array of three dimensions?
`array(data = integer(), dim = integer(3))`?

Or perhaps here the verbose form is actually easier to understand?

Agreed that it's odd that this isn't standardised in the community.
I also noticed for newbies, the verbose `an integer vector of length 1` form is really jarring.

Apologies for going off-topic here.

**Comment by berndbischl** [comment]
> So how would you document, say, an expected integer array of three dimensions?
> array(data = integer(), dim = integer(3))?

hmm, we never defined this (for us) because it never appeared that much.
i would probably use integer(10, 20, 5) for a 3dim int array, when I KNOW the sizes of the dims. 
(to be near to the 1-dim vector case)

**Comment by maxheld83** [comment]
thanks so much!
