### ISSUE TITLE
Feature request: accept null in assert class

### ISSUE THREAD

**Issue by MansMeg** [mllg/checkmate#97]
Hi!

Thanks again for a really good package. Now I have multiple times run into that I have an argument that either is ```NULL``` or a specific object. The most common situation is in constructor functions where I want to check if there are a argument used, and if it is used I check that it is a list as an example.

So it would be great to have the argument ```null.ok``` in the ```assert_class()``` function.

/Måns

**Comment by mllg** [comment]
Sure. Will be released with v1.9.0.
